Update Publish.yml

diff --git a/.github/workflows/Publish.yml b/.github/workflows/Publish.yml
--- a/.github/workflows/Publish.yml
+++ b/.github/workflows/Publish.yml
@@ -17,18 +17,22 @@ jobs:
       - name: Get Environment Variables
         run: |
           $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
-
           "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV
-          
+
       - name: Set up .NET
-        uses: actions/setup-dotnet@v1
+        uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
 
       - name: Download Dalamud Latest
         run: |
           Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
-          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
+          if ($?) {
+            Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
+          } else {
+            Write-Error "Failed to download Dalamud Latest"
+            exit 1
+          }
 
       - name: Restore Nuget Packages
         run: dotnet restore BasicRotations/RebornRotations.csproj
